compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

packageExtensions:
  eslint-config-airbnb-base@*:
    dependencies:
      eslint-plugin-import: "*"
  eslint-module-utils@*:
    dependencies:
      eslint: "*"
      eslint-import-resolver-node: "*"
      resolve: "*"
  folio@*:
    dependencies:
      minimatch: "*"

yarnPath: .yarn/releases/yarn-4.9.1.cjs
